recent_image_folder: /home/fazrigading/ResearchExperiment/palmOilFruitCounting/dataset/images
recent_label_folder: /home/fazrigading/ResearchExperiment/palmOilFruitCounting/dataset/sam_baseplus/labels_seg
